### ISSUE TITLE
Errors running any 'athom' command

### ISSUE THREAD

**Issue by MikeOne** [athombv/athom-cli#3]
Hi,

Just installed the cli version, following the instructions. No issues visible in the NPM install, however, If I try to login I get the following:

```
athom login

/usr/local/lib/node_modules/athom-cli/node_modules/jsop/node_modules/observed/lib/observed.js:77
  Object.observe(this.subject, this.onchange);
         ^
TypeError: Object function Object() { [native code] } has no method 'observe'
    at Observable._bind (/usr/local/lib/node_modules/athom-cli/node_modules/jsop/node_modules/observed/lib/observed.js:77:10)
    at new Observable (/usr/local/lib/node_modules/athom-cli/node_modules/jsop/node_modules/observed/lib/observed.js:41:8)
    at Observable (/usr/local/lib/node_modules/athom-cli/node_modules/jsop/node_modules/observed/lib/observed.js:36:12)
    at module.exports (/usr/local/lib/node_modules/athom-cli/node_modules/jsop/index.js:13:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/athom-cli/lib/settings.js:10:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I installed with sudo on a mac. Any ideas what I'm missing here?

**Comment by WeeJeWel** [comment]
Please upgrade to nodejs 0.12
